# Generated by Django 3.2.25 on 2024-05-19 19:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
