# Generated by Django 3.2.25 on 2024-05-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='title',
        ),
    ]
